# Fly.io deployment configuration for Dealer Logic
app = "dealer-logic"
primary_region = "phx"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile.production"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  PRODUCTION_DOMAIN = "dealerlogic.io"
  API_BASE_URL = "https://api.dealerlogic.io"
  WEBHOOK_BASE_URL = "https://hooks.dealerlogic.io"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = false

[mounts]
  source = "dealer_logic_data"
  destination = "/data"