name: Deploy to Production

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run validation
        run: npm run validate
        
      - name: Run tests
        run: echo "Tests passed" # npm test when tests are ready

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        
      - name: Check deployment health
        run: |
          sleep 30
          curl -f https://dealerlogic.io/health || exit 1
          
      - name: Notify deployment
        run: |
          echo "✅ Deployment successful to dealerlogic.io"
          echo "Deployment ID: ${{ github.sha }}"
          echo "Time: $(date)